default_context:
  project_name: 'Brokis Auction Systen'
  project_slug: 'brokis-as'
  domain_main: 'as.brokis.com'
  domain_staging: 'stag.as.brokis.com'
  docker_swarm_stack_name_main: 'as-brokis-com'
  docker_swarm_stack_name_staging: 'stag-as-brokis-com'
  secret_key: 'qw'
  first_superuser: 'info.brokis@gmail.com'
  first_superuser_password: 'qw'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.as.brokis.com", "https://stag.as.brokis.com", "https://as.brokis.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: 'smtp.gmail.com'
  smtp_user: 'info.brokis@gmail.com'
  smtp_password: 'Kalimba10$'
  smtp_emails_from_email: 'info.brokis@gmail.com'
  postgres_password: 'qw'
  pgadmin_default_user: 'info.brokis@gmail.com'
  pgadmin_default_user_password: 'qw'
  traefik_constraint_tag: 'as.brokis.com'
  traefik_constraint_tag_staging: 'stag.as.brokis.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:qw'
  sentry_dsn: ''
  docker_image_prefix: 'brokis_as_'
  docker_image_backend: 'brokis_as_backend'
  docker_image_celeryworker: 'brokis_as_celeryworker'
  docker_image_frontend: 'brokis_as_frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
