"""Remove relationship back_prop item user

Revision ID: 80fdaaf8f929
Revises: 2d8b9e7d6d88
Create Date: 2022-04-06 23:19:33.477600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80fdaaf8f929'
down_revision = '2d8b9e7d6d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
