"""Fix models: back_pop auction user

Revision ID: 9096b4b24ac7
Revises: b35498a9f070
Create Date: 2022-04-06 22:50:11.144004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9096b4b24ac7'
down_revision = 'b35498a9f070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
