"""Fix models: back_pop auction user

Revision ID: b35498a9f070
Revises: 25e45ea164b7
Create Date: 2022-04-06 22:48:45.247594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35498a9f070'
down_revision = '25e45ea164b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
