"""Integrate status

Revision ID: b926d27a22d4
Revises: 80fdaaf8f929
Create Date: 2022-04-07 13:36:06.205643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b926d27a22d4'
down_revision = '80fdaaf8f929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('auction', 'is_active')
    op.drop_column('auction', 'is_published')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction', sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('auction', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('auction', 'status')
    # ### end Alembic commands ###
