"""Add auction and bid models

Revision ID: e3d58eefc9b9
Revises: d4867f3a4c0a
Create Date: 2022-04-06 22:13:57.318858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d58eefc9b9'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('cycle_duration', sa.Integer(), nullable=True),
    sa.Column('max_cycle_number', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auction_description'), 'auction', ['description'], unique=False)
    op.create_index(op.f('ix_auction_id'), 'auction', ['id'], unique=False)
    op.create_index(op.f('ix_auction_title'), 'auction', ['title'], unique=False)
    op.create_table('bid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_date', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('bidder_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bidder_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_id'), 'bid', ['id'], unique=False)
    op.add_column('item', sa.Column('start_price', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('picture_url', sa.String(), nullable=True))
    op.add_column('item', sa.Column('auction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item', 'auction', ['auction_id'], ['id'])
    op.add_column('user', sa.Column('first_name', sa.String(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_user_full_name', table_name='user')
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.create_index('ix_user_full_name', 'user', ['full_name'], unique=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'first_name')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'auction_id')
    op.drop_column('item', 'picture_url')
    op.drop_column('item', 'start_price')
    op.drop_index(op.f('ix_bid_id'), table_name='bid')
    op.drop_table('bid')
    op.drop_index(op.f('ix_auction_title'), table_name='auction')
    op.drop_index(op.f('ix_auction_id'), table_name='auction')
    op.drop_index(op.f('ix_auction_description'), table_name='auction')
    op.drop_table('auction')
    # ### end Alembic commands ###
