"""Model not imported fix: add models to __init__.py

Revision ID: f79c3b0d6463
Revises: 9096b4b24ac7
Create Date: 2022-04-06 23:03:59.140305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79c3b0d6463'
down_revision = '9096b4b24ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
